source 'http://rubygems.org'
gem 'allure-rspec'
gem 'capybara', '<3.3'
gem 'chromedriver-helper'
gem 'faker'
gem 'rake'
gem 'rspec'
gem 'rubocop'
gem 'selenium-webdriver', '~>3.4'
gem 'site_prism', '2.15.1'
